import { db } from "@workspace/db";
import {
  wilayasTable,
  categoriesTable,
  sellersTable,
  productsTable,
  marketPricesTable,
} from "@workspace/db";
import { logger } from "../lib/logger";

const wilayas = [
  { id: "alger", code: 16, name: "Alger", nameAr: "الجزائر", region: "Centre" },
  { id: "oran", code: 31, name: "Oran", nameAr: "وهران", region: "Ouest" },
  { id: "constantine", code: 25, name: "Constantine", nameAr: "قسنطينة", region: "Est" },
  { id: "annaba", code: 23, name: "Annaba", nameAr: "عنابة", region: "Est" },
  { id: "blida", code: 9, name: "Blida", nameAr: "البليدة", region: "Centre" },
  { id: "batna", code: 5, name: "Batna", nameAr: "باتنة", region: "Est" },
  { id: "djelfa", code: 17, name: "Djelfa", nameAr: "الجلفة", region: "Centre" },
  { id: "setif", code: 19, name: "Sétif", nameAr: "سطيف", region: "Est" },
  { id: "sidi-bel-abbes", code: 22, name: "Sidi Bel Abbès", nameAr: "سيدي بلعباس", region: "Ouest" },
  { id: "biskra", code: 7, name: "Biskra", nameAr: "بسكرة", region: "Sud-Est" },
  { id: "tlemcen", code: 13, name: "Tlemcen", nameAr: "تلمسان", region: "Ouest" },
  { id: "tiaret", code: 14, name: "Tiaret", nameAr: "تيارت", region: "Ouest" },
  { id: "bejaia", code: 6, name: "Béjaïa", nameAr: "بجاية", region: "Est" },
  { id: "tizi-ouzou", code: 15, name: "Tizi Ouzou", nameAr: "تيزي وزو", region: "Centre" },
  { id: "el-oued", code: 39, name: "El Oued", nameAr: "الوادي", region: "Sud-Est" },
  { id: "ouargla", code: 30, name: "Ouargla", nameAr: "ورقلة", region: "Sud" },
  { id: "ghardaia", code: 47, name: "Ghardaïa", nameAr: "غرداية", region: "Sud" },
  { id: "medea", code: 26, name: "Médéa", nameAr: "المدية", region: "Centre" },
  { id: "mostaganem", code: 27, name: "Mostaganem", nameAr: "مستغانم", region: "Ouest" },
  { id: "msila", code: 28, name: "M'Sila", nameAr: "المسيلة", region: "Centre" },
  { id: "mascara", code: 29, name: "Mascara", nameAr: "معسكر", region: "Ouest" },
  { id: "skikda", code: 21, name: "Skikda", nameAr: "سكيكدة", region: "Est" },
  { id: "laghouat", code: 3, name: "Laghouat", nameAr: "الأغواط", region: "Centre" },
  { id: "bechar", code: 8, name: "Béchar", nameAr: "بشار", region: "Sud-Ouest" },
  { id: "tamanrasset", code: 11, name: "Tamanrasset", nameAr: "تمنراست", region: "Grand Sud" },
  { id: "tebessa", code: 12, name: "Tébessa", nameAr: "تبسة", region: "Est" },
  { id: "guelma", code: 24, name: "Guelma", nameAr: "قالمة", region: "Est" },
  { id: "souk-ahras", code: 41, name: "Souk Ahras", nameAr: "سوق أهراس", region: "Est" },
  { id: "relizane", code: 48, name: "Relizane", nameAr: "غليزان", region: "Ouest" },
  { id: "oum-el-bouaghi", code: 4, name: "Oum El Bouaghi", nameAr: "أم البواقي", region: "Est" },
];

const categories = [
  { id: "legumes", name: "Légumes", nameAr: "خضروات", icon: "🥦", description: "Tomates, pommes de terre, oignons, carottes et tous les légumes frais" },
  { id: "fruits", name: "Fruits", nameAr: "فواكه", icon: "🍊", description: "Agrumes, raisins, dattes, figues et tous les fruits saisonniers" },
  { id: "cereales", name: "Céréales & Légumineuses", nameAr: "حبوب وبقوليات", icon: "🌾", description: "Blé, orge, lentilles, pois chiches, fèves" },
  { id: "elevage", name: "Élevage", nameAr: "مواشي", icon: "🐄", description: "Bovins, ovins, caprins, volailles et produits d'élevage" },
  { id: "equipement", name: "Équipement Agricole", nameAr: "معدات زراعية", icon: "🚜", description: "Tracteurs, outils, systèmes d'irrigation et équipements divers" },
  { id: "semences", name: "Semences & Intrants", nameAr: "بذور ومدخلات", icon: "🌱", description: "Semences sélectionnées, engrais, pesticides bio et intrants agricoles" },
  { id: "huiles", name: "Huiles & Produits Transformés", nameAr: "زيوت ومنتجات مصنعة", icon: "🫒", description: "Huile d'olive, huile d'argan, conserves, miel et produits transformés" },
  { id: "herbes", name: "Herbes & Épices", nameAr: "أعشاب وتوابل", icon: "🌿", description: "Coriandre, cumin, ras el hanout, menthe et herbes aromatiques" },
];

const sellers = [
  {
    id: "sel-1",
    name: "Ahmed Boudiaf",
    wilayaId: "setif",
    phone: "0555 23 45 67",
    bio: "Agriculteur depuis 20 ans dans la région de Sétif. Spécialisé dans la production de blé dur et de légumes. Certifié agriculture biologique depuis 2018.",
    rating: "4.8",
    reviewCount: 124,
    productCount: 12,
    verified: true,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=AhmedBoudiaf",
  },
  {
    id: "sel-2",
    name: "Fatima Benali",
    wilayaId: "tizi-ouzou",
    phone: "0661 87 32 10",
    bio: "Productrice d'huile d'olive de qualité supérieure en Kabylie. Oliveraie familiale de 5 hectares avec des variétés anciennes. Huile artisanale pressée à froid.",
    rating: "4.9",
    reviewCount: 89,
    productCount: 5,
    verified: true,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=FatimaBenali",
  },
  {
    id: "sel-3",
    name: "Mohamed Cherif",
    wilayaId: "biskra",
    phone: "0770 45 23 89",
    bio: "Phoeniculteur dans la région de Biskra. Plus de 500 palmiers dattiers variétés Deglet Nour et Ghars. Export vers l'Europe et le Moyen-Orient.",
    rating: "4.7",
    reviewCount: 201,
    productCount: 8,
    verified: true,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=MohamedCherif",
  },
  {
    id: "sel-4",
    name: "Rachid Hadj",
    wilayaId: "blida",
    phone: "0550 11 78 34",
    bio: "Maraîcher dans la Mitidja. Production de tomates, poivrons et courgettes sous serre. Livraison possible à Alger et environs.",
    rating: "4.5",
    reviewCount: 67,
    productCount: 15,
    verified: false,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=RachidHadj",
  },
  {
    id: "sel-5",
    name: "Khadija Mansouri",
    wilayaId: "medea",
    phone: "0660 34 56 78",
    bio: "Éleveuse de moutons et productrice de laine et viande ovine à Médéa. Race Ouled Djellal certifiée. Production de 200 têtes par an.",
    rating: "4.6",
    reviewCount: 45,
    productCount: 6,
    verified: true,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=KhadijaMansouri",
  },
  {
    id: "sel-6",
    name: "Omar Bekkali",
    wilayaId: "tlemcen",
    phone: "0773 89 01 23",
    bio: "Vigneron dans la région de Tlemcen. Production de raisin de table et de cuve. Variétés traditionnelles algériennes et importées.",
    rating: "4.4",
    reviewCount: 38,
    productCount: 4,
    verified: false,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=OmarBekkali",
  },
  {
    id: "sel-7",
    name: "Youcef Bensalem",
    wilayaId: "constantine",
    phone: "0556 67 89 01",
    bio: "Fournisseur de semences sélectionnées et d'intrants agricoles biologiques à Constantine. 15 ans d'expérience dans l'agrofourniture.",
    rating: "4.7",
    reviewCount: 156,
    productCount: 20,
    verified: true,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=YoucefBensalem",
  },
  {
    id: "sel-8",
    name: "Zineb Meziane",
    wilayaId: "bejaia",
    phone: "0664 45 67 89",
    bio: "Apicultrice et herboriste en Kabylie. Production de miel sauvage de montagne et herbes médicinales. Certifiée Agriculture Biologique.",
    rating: "5.0",
    reviewCount: 73,
    productCount: 9,
    verified: true,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=ZinebMeziane",
  },
  {
    id: "sel-9",
    name: "Abdelkader Lakehal",
    wilayaId: "oran",
    phone: "0770 12 34 56",
    bio: "Agrumiculteur dans la région d'Oran. Production d'oranges, clémentines et citrons. 20 hectares de vergers en agriculture raisonnée.",
    rating: "4.3",
    reviewCount: 92,
    productCount: 7,
    verified: true,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=AbdelkaderLakehal",
  },
  {
    id: "sel-10",
    name: "Nadia Boudaoud",
    wilayaId: "el-oued",
    phone: "0554 89 01 23",
    bio: "Maraîchage dans la région du Souf. Spécialisée dans les légumes de désert: navets, carottes et pommes de terre de sable.",
    rating: "4.6",
    reviewCount: 51,
    productCount: 8,
    verified: false,
    profileImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=NadiaBoudaoud",
  },
];

const products = [
  // Légumes
  {
    id: "prod-1",
    name: "Tomates fraîches",
    nameAr: "طماطم طازجة",
    description: "Tomates rondes de qualité supérieure, cultivées en plein champ dans la Mitidja. Riches en lycopène, sans pesticides. Idéales pour la cuisine algérienne traditionnelle.",
    categoryId: "legumes",
    sellerId: "sel-4",
    wilayaId: "blida",
    price: "120.00",
    unit: "kg",
    minOrder: "5",
    stock: "2000",
    images: ["https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&q=80", "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&q=80"],
    featured: true,
    organic: false,
    rating: "4.5",
    reviewCount: 34,
    tags: ["frais", "plein-champ", "mitidja"],
  },
  {
    id: "prod-2",
    name: "Pommes de terre Sable",
    nameAr: "بطاطا الرمال",
    description: "Pommes de terre cultivées dans le sable du Souf, reconnues pour leur goût exceptionnel. Variété Désirée et Spunta. Production annuelle certifiée.",
    categoryId: "legumes",
    sellerId: "sel-10",
    wilayaId: "el-oued",
    price: "95.00",
    unit: "kg",
    minOrder: "10",
    stock: "5000",
    images: ["https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80"],
    featured: true,
    organic: false,
    rating: "4.8",
    reviewCount: 89,
    tags: ["souf", "sable", "premier-choix"],
  },
  {
    id: "prod-3",
    name: "Oignons secs",
    nameAr: "بصل جاف",
    description: "Oignons secs de la région de Sétif, reconnus pour leur excellente conservation. Calibre moyen et gros disponibles. Sac de 10kg ou 25kg.",
    categoryId: "legumes",
    sellerId: "sel-1",
    wilayaId: "setif",
    price: "75.00",
    unit: "kg",
    minOrder: "10",
    stock: "3000",
    images: ["https://images.unsplash.com/photo-1508747703725-719777637510?w=600&q=80"],
    featured: false,
    organic: false,
    rating: "4.2",
    reviewCount: 22,
    tags: ["conservation", "setif", "calibre-moyen"],
  },
  {
    id: "prod-4",
    name: "Carottes biologiques",
    nameAr: "جزر بيولوجي",
    description: "Carottes biologiques certifiées, cultivées sans pesticides dans la plaine de Annaba. Riches en bêta-carotène. Conditionnées en bottes de 500g.",
    categoryId: "legumes",
    sellerId: "sel-4",
    wilayaId: "blida",
    price: "90.00",
    unit: "kg",
    minOrder: "5",
    stock: "800",
    images: ["https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=600&q=80"],
    featured: false,
    organic: true,
    rating: "4.6",
    reviewCount: 18,
    tags: ["bio", "certifié", "sans-pesticides"],
  },
  {
    id: "prod-5",
    name: "Poivrons doux tricolores",
    nameAr: "فلفل حلو ثلاثي الألوان",
    description: "Poivrons rouges, jaunes et verts cultivés sous serre à Blida. Production continue toute l'année. Calibre AA+ exportation.",
    categoryId: "legumes",
    sellerId: "sel-4",
    wilayaId: "blida",
    price: "180.00",
    unit: "kg",
    minOrder: "5",
    stock: "600",
    images: ["https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&q=80"],
    featured: true,
    organic: false,
    rating: "4.7",
    reviewCount: 28,
    tags: ["serre", "blida", "export"],
  },
  // Fruits
  {
    id: "prod-6",
    name: "Dattes Deglet Nour",
    nameAr: "تمر دقلة نور",
    description: "La reine des dattes algériennes. Variété Deglet Nour de Biskra, translucide, dorée, au goût de miel incomparable. Conditionnée en barquette de 500g ou vrac.",
    categoryId: "fruits",
    sellerId: "sel-3",
    wilayaId: "biskra",
    price: "850.00",
    unit: "kg",
    minOrder: "2",
    stock: "3000",
    images: ["https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?w=600&q=80", "https://images.unsplash.com/photo-1560717845-968823efbee1?w=600&q=80"],
    featured: true,
    organic: true,
    rating: "4.9",
    reviewCount: 145,
    tags: ["deglet-nour", "biskra", "premium", "export"],
  },
  {
    id: "prod-7",
    name: "Oranges navel",
    nameAr: "برتقال نابل",
    description: "Oranges navel d'Oran, sucrées et sans pépins. Idéales pour le jus et la consommation directe. Verger certifié agriculture raisonnée.",
    categoryId: "fruits",
    sellerId: "sel-9",
    wilayaId: "oran",
    price: "120.00",
    unit: "kg",
    minOrder: "10",
    stock: "10000",
    images: ["https://images.unsplash.com/photo-1547514701-42782101795e?w=600&q=80"],
    featured: true,
    organic: false,
    rating: "4.4",
    reviewCount: 67,
    tags: ["oran", "navel", "jus", "sans-pepins"],
  },
  {
    id: "prod-8",
    name: "Raisin de table Aïn Bessem",
    nameAr: "عنب عين البسام",
    description: "Raisin blanc de table d'Aïn Bessem, variété Dattier de Beyrouth. Grains longs et sucrés, peau fine. Récolte août-septembre.",
    categoryId: "fruits",
    sellerId: "sel-6",
    wilayaId: "tlemcen",
    price: "250.00",
    unit: "kg",
    minOrder: "5",
    stock: "2000",
    images: ["https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=600&q=80"],
    featured: false,
    organic: false,
    rating: "4.5",
    reviewCount: 33,
    tags: ["raisin", "tlemcen", "table", "saisonnier"],
  },
  {
    id: "prod-9",
    name: "Figues fraîches de Kabylie",
    nameAr: "تين طازج من القبائل",
    description: "Figues violettes de montagne en Kabylie. Variété locale très sucrée. Disponibles août-septembre. Livraison express 24h.",
    categoryId: "fruits",
    sellerId: "sel-2",
    wilayaId: "tizi-ouzou",
    price: "200.00",
    unit: "kg",
    minOrder: "3",
    stock: "500",
    images: ["https://images.unsplash.com/photo-1481349518771-20055b2a7b24?w=600&q=80"],
    featured: false,
    organic: true,
    rating: "4.8",
    reviewCount: 41,
    tags: ["kabylie", "saisonnier", "montagne", "bio"],
  },
  {
    id: "prod-10",
    name: "Clémentines de Mostaganem",
    nameAr: "كليمانتين مستغانم",
    description: "Clémentines IGP de la région de Mostaganem. Sucrées, faciles à peler, riches en vitamine C. Boîtes de 10kg disponibles.",
    categoryId: "fruits",
    sellerId: "sel-9",
    wilayaId: "mostaganem",
    price: "150.00",
    unit: "kg",
    minOrder: "10",
    stock: "5000",
    images: ["https://images.unsplash.com/photo-1580052614034-c55d20bfee3b?w=600&q=80"],
    featured: true,
    organic: false,
    rating: "4.7",
    reviewCount: 82,
    tags: ["mostaganem", "igp", "vitamine-c", "hiver"],
  },
  // Céréales
  {
    id: "prod-11",
    name: "Blé dur de Sétif",
    nameAr: "قمح صلب من سطيف",
    description: "Blé dur de haute qualité produit dans les plaines de Sétif. Teneur en protéines élevée (14%). Idéal pour la semoule et les pâtes. Certifié non OGM.",
    categoryId: "cereales",
    sellerId: "sel-1",
    wilayaId: "setif",
    price: "5500.00",
    unit: "quintal",
    minOrder: "1",
    stock: "500",
    images: ["https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&q=80"],
    featured: true,
    organic: false,
    rating: "4.7",
    reviewCount: 56,
    tags: ["setif", "non-ogm", "haute-proteine", "semoule"],
  },
  {
    id: "prod-12",
    name: "Lentilles vertes de Khenchela",
    nameAr: "عدس أخضر من خنشلة",
    description: "Lentilles vertes de montagne de la région de Khenchela. Petite lentille très appréciée pour sa saveur. Sans pesticides, séchées naturellement.",
    categoryId: "cereales",
    sellerId: "sel-1",
    wilayaId: "batna",
    price: "280.00",
    unit: "kg",
    minOrder: "10",
    stock: "2000",
    images: ["https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=600&q=80"],
    featured: false,
    organic: true,
    rating: "4.6",
    reviewCount: 29,
    tags: ["montagne", "bio", "khenchela", "sans-pesticides"],
  },
  {
    id: "prod-13",
    name: "Pois chiches secs de Tiaret",
    nameAr: "حمص جاف من تيارت",
    description: "Gros pois chiches secs de Tiaret, variété locale Hommous Kbir. Idéaux pour le couscous et la harira. Calibre 9mm+.",
    categoryId: "cereales",
    sellerId: "sel-7",
    wilayaId: "tiaret",
    price: "220.00",
    unit: "kg",
    minOrder: "5",
    stock: "3000",
    images: ["https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=600&q=80"],
    featured: false,
    organic: false,
    rating: "4.4",
    reviewCount: 44,
    tags: ["tiaret", "couscous", "harira", "gros-calibre"],
  },
  // Élevage
  {
    id: "prod-14",
    name: "Moutons Ouled Djellal",
    nameAr: "أغنام أولاد جلال",
    description: "Moutons de race Ouled Djellal, élevés en plein air dans les steppes de Médéa. Viande rouge de qualité supérieure. Poids vif: 35-50 kg.",
    categoryId: "elevage",
    sellerId: "sel-5",
    wilayaId: "medea",
    price: "45000.00",
    unit: "tête",
    minOrder: "1",
    stock: "150",
    images: ["https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&q=80"],
    featured: true,
    organic: false,
    rating: "4.6",
    reviewCount: 23,
    tags: ["ouled-djellal", "viande-rouge", "steppe", "race-pure"],
  },
  {
    id: "prod-15",
    name: "Poulets fermiers Label Rouge",
    nameAr: "دجاج فلاحي",
    description: "Poulets fermiers élevés au grain dans la plaine de Blida. Alimentation 100% naturelle, sans hormones. Poids: 2-2.5 kg. Disponibles entiers ou découpés.",
    categoryId: "elevage",
    sellerId: "sel-4",
    wilayaId: "blida",
    price: "650.00",
    unit: "kg",
    minOrder: "5",
    stock: "200",
    images: ["https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=600&q=80"],
    featured: false,
    organic: false,
    rating: "4.7",
    reviewCount: 37,
    tags: ["fermier", "sans-hormones", "blida", "grain"],
  },
  // Équipement
  {
    id: "prod-16",
    name: "Système d'irrigation goutte-à-goutte",
    nameAr: "نظام ري بالتقطير",
    description: "Kit complet d'irrigation goutte-à-goutte pour 1 hectare. Inclut tuyaux, goutteurs, filtre et manomètre. Marque Netafim. Installation incluse.",
    categoryId: "equipement",
    sellerId: "sel-7",
    wilayaId: "constantine",
    price: "85000.00",
    unit: "kit",
    minOrder: "1",
    stock: "20",
    images: ["https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=600&q=80"],
    featured: true,
    organic: false,
    rating: "4.8",
    reviewCount: 19,
    tags: ["irrigation", "economie-eau", "1-hectare", "installation"],
  },
  {
    id: "prod-17",
    name: "Motoculteur diesel 7CV",
    nameAr: "محرث بمحرك ديزل",
    description: "Motoculteur diesel 7CV pour petites et moyennes exploitations. Avec charrue, cultivateur et buttoir. Garantie 2 ans pièces et main d'oeuvre.",
    categoryId: "equipement",
    sellerId: "sel-7",
    wilayaId: "constantine",
    price: "120000.00",
    unit: "unité",
    minOrder: "1",
    stock: "10",
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
    featured: false,
    organic: false,
    rating: "4.5",
    reviewCount: 12,
    tags: ["diesel", "garantie", "polyvalent", "petite-exploitation"],
  },
  // Semences
  {
    id: "prod-18",
    name: "Semences de tomate hybride F1",
    nameAr: "بذور طماطم هجين F1",
    description: "Semences de tomates hybrides F1 à haut rendement. Résistantes aux maladies (verticilliose, fusariose). Variété Rouge Royal. 10g = 3000 graines.",
    categoryId: "semences",
    sellerId: "sel-7",
    wilayaId: "constantine",
    price: "2500.00",
    unit: "sachet 10g",
    minOrder: "1",
    stock: "500",
    images: ["https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=600&q=80"],
    featured: false,
    organic: false,
    rating: "4.7",
    reviewCount: 65,
    tags: ["hybride", "haut-rendement", "resistance-maladies"],
  },
  {
    id: "prod-19",
    name: "Engrais organique compost",
    nameAr: "سماد عضوي",
    description: "Compost organique certifié 100% naturel. Améliore la structure du sol et stimule la vie microbienne. Sac de 40kg. Idéal pour maraîchage et arboriculture.",
    categoryId: "semences",
    sellerId: "sel-1",
    wilayaId: "setif",
    price: "1200.00",
    unit: "sac 40kg",
    minOrder: "5",
    stock: "300",
    images: ["https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80"],
    featured: false,
    organic: true,
    rating: "4.6",
    reviewCount: 48,
    tags: ["bio", "compost", "sol", "naturel"],
  },
  // Huiles & produits transformés
  {
    id: "prod-20",
    name: "Huile d'olive vierge extra Kabylie",
    nameAr: "زيت زيتون بكر ممتاز من القبائل",
    description: "Huile d'olive vierge extra pressée à froid. Acidité inférieure à 0.3%. Variétés Sigoise et Chemlal. Médaillée d'or au Concours Mondial de Bruxelles 2023.",
    categoryId: "huiles",
    sellerId: "sel-2",
    wilayaId: "tizi-ouzou",
    price: "1800.00",
    unit: "litre",
    minOrder: "2",
    stock: "500",
    images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80"],
    featured: true,
    organic: true,
    rating: "5.0",
    reviewCount: 78,
    tags: ["vierge-extra", "presse-a-froid", "medaille-or", "kabylie"],
  },
  {
    id: "prod-21",
    name: "Miel de montagne Kabylie",
    nameAr: "عسل جبلي قبائلي",
    description: "Miel toutes fleurs de montagne récolté en Kabylie. 100% naturel, non chauffé, non filtré. Certifié Agriculture Biologique. Pot de 500g ou 1kg.",
    categoryId: "huiles",
    sellerId: "sel-8",
    wilayaId: "bejaia",
    price: "3500.00",
    unit: "kg",
    minOrder: "1",
    stock: "200",
    images: ["https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80"],
    featured: true,
    organic: true,
    rating: "5.0",
    reviewCount: 67,
    tags: ["bio", "montagne", "naturel", "non-chauffe"],
  },
  // Herbes & Épices
  {
    id: "prod-22",
    name: "Cumin de Tébessa",
    nameAr: "كمون من تبسة",
    description: "Cumin de qualité supérieure de la région de Tébessa. Séché naturellement au soleil. Vendu en graines ou moulu. Arôme intense.",
    categoryId: "herbes",
    sellerId: "sel-8",
    wilayaId: "bejaia",
    price: "450.00",
    unit: "kg",
    minOrder: "1",
    stock: "500",
    images: ["https://images.unsplash.com/photo-1588421357574-87938a86fa28?w=600&q=80"],
    featured: false,
    organic: true,
    rating: "4.8",
    reviewCount: 34,
    tags: ["bio", "seche-soleil", "arome-intense", "tebessa"],
  },
  {
    id: "prod-23",
    name: "Menthe fraîche de Médéa",
    nameAr: "نعناع طازج من المدية",
    description: "Menthe fraîche de la région de Médéa. Parfum intense. Disponible en bottes fraîches (livraison 24h) ou séchée. Idéale pour le thé et la cuisine.",
    categoryId: "herbes",
    sellerId: "sel-5",
    wilayaId: "medea",
    price: "150.00",
    unit: "kg",
    minOrder: "2",
    stock: "300",
    images: ["https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&q=80"],
    featured: false,
    organic: false,
    rating: "4.5",
    reviewCount: 27,
    tags: ["the", "cuisine", "frais", "medea"],
  },
  {
    id: "prod-24",
    name: "Ras el Hanout artisanal",
    nameAr: "رأس الحانوت تقليدي",
    description: "Mélange traditionnel ras el hanout composé de 27 épices. Recette ancestrale de Kabylie. Sans colorants ni conservateurs. Pot de 200g.",
    categoryId: "herbes",
    sellerId: "sel-8",
    wilayaId: "bejaia",
    price: "850.00",
    unit: "pot 200g",
    minOrder: "1",
    stock: "150",
    images: ["https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80"],
    featured: false,
    organic: true,
    rating: "4.9",
    reviewCount: 52,
    tags: ["artisanal", "traditionnel", "27-epices", "sans-conservateurs"],
  },
];

const marketPrices = [
  { id: "mp-1", productName: "Tomates", productNameAr: "طماطم", categoryName: "Légumes", priceMin: "80", priceMax: "150", unit: "kg", trend: "up", changePercent: "5.3", wilayaName: "Alger" },
  { id: "mp-2", productName: "Pommes de terre", productNameAr: "بطاطا", categoryName: "Légumes", priceMin: "60", priceMax: "110", unit: "kg", trend: "stable", changePercent: "0.5", wilayaName: "Alger" },
  { id: "mp-3", productName: "Oignons", productNameAr: "بصل", categoryName: "Légumes", priceMin: "55", priceMax: "90", unit: "kg", trend: "down", changePercent: "-3.2", wilayaName: "Alger" },
  { id: "mp-4", productName: "Carottes", productNameAr: "جزر", categoryName: "Légumes", priceMin: "70", priceMax: "120", unit: "kg", trend: "up", changePercent: "2.1", wilayaName: "Alger" },
  { id: "mp-5", productName: "Dattes Deglet Nour", productNameAr: "تمر دقلة نور", categoryName: "Fruits", priceMin: "750", priceMax: "950", unit: "kg", trend: "up", changePercent: "8.5", wilayaName: "Biskra" },
  { id: "mp-6", productName: "Oranges", productNameAr: "برتقال", categoryName: "Fruits", priceMin: "100", priceMax: "180", unit: "kg", trend: "down", changePercent: "-4.1", wilayaName: "Oran" },
  { id: "mp-7", productName: "Raisin de table", productNameAr: "عنب", categoryName: "Fruits", priceMin: "200", priceMax: "350", unit: "kg", trend: "stable", changePercent: "0.8", wilayaName: "Tlemcen" },
  { id: "mp-8", productName: "Blé dur", productNameAr: "قمح صلب", categoryName: "Céréales", priceMin: "5200", priceMax: "5800", unit: "quintal", trend: "up", changePercent: "3.7", wilayaName: "Sétif" },
  { id: "mp-9", productName: "Orge", productNameAr: "شعير", categoryName: "Céréales", priceMin: "3800", priceMax: "4200", unit: "quintal", trend: "stable", changePercent: "1.2", wilayaName: "Sétif" },
  { id: "mp-10", productName: "Pois chiches", productNameAr: "حمص", categoryName: "Céréales", priceMin: "180", priceMax: "280", unit: "kg", trend: "up", changePercent: "6.8", wilayaName: "Tiaret" },
  { id: "mp-11", productName: "Lentilles", productNameAr: "عدس", categoryName: "Céréales", priceMin: "220", priceMax: "320", unit: "kg", trend: "down", changePercent: "-2.5", wilayaName: "Batna" },
  { id: "mp-12", productName: "Huile d'olive", productNameAr: "زيت زيتون", categoryName: "Huiles", priceMin: "1500", priceMax: "2200", unit: "litre", trend: "up", changePercent: "12.3", wilayaName: "Tizi Ouzou" },
  { id: "mp-13", productName: "Mouton (vif)", productNameAr: "خروف حي", categoryName: "Élevage", priceMin: "38000", priceMax: "55000", unit: "tête", trend: "up", changePercent: "9.2", wilayaName: "Médéa" },
  { id: "mp-14", productName: "Poulet fermier", productNameAr: "دجاج فلاحي", categoryName: "Élevage", priceMin: "550", priceMax: "750", unit: "kg", trend: "stable", changePercent: "0.3", wilayaName: "Blida" },
  { id: "mp-15", productName: "Miel", productNameAr: "عسل", categoryName: "Huiles", priceMin: "2800", priceMax: "4500", unit: "kg", trend: "up", changePercent: "5.6", wilayaName: "Béjaïa" },
  { id: "mp-16", productName: "Courgettes", productNameAr: "كوسة", categoryName: "Légumes", priceMin: "90", priceMax: "160", unit: "kg", trend: "down", changePercent: "-7.4", wilayaName: "Alger" },
  { id: "mp-17", productName: "Poivrons", productNameAr: "فلفل", categoryName: "Légumes", priceMin: "150", priceMax: "250", unit: "kg", trend: "up", changePercent: "4.2", wilayaName: "Blida" },
  { id: "mp-18", productName: "Clémentines", productNameAr: "كليمانتين", categoryName: "Fruits", priceMin: "120", priceMax: "200", unit: "kg", trend: "down", changePercent: "-3.8", wilayaName: "Mostaganem" },
  { id: "mp-19", productName: "Figues", productNameAr: "تين", categoryName: "Fruits", priceMin: "180", priceMax: "350", unit: "kg", trend: "stable", changePercent: "1.1", wilayaName: "Tizi Ouzou" },
  { id: "mp-20", productName: "Cumin", productNameAr: "كمون", categoryName: "Épices", priceMin: "380", priceMax: "600", unit: "kg", trend: "up", changePercent: "7.9", wilayaName: "Tébessa" },
];

export async function seedDatabase() {
  try {
    logger.info("Starting database seeding...");

    // Seed wilayas
    for (const w of wilayas) {
      await db.insert(wilayasTable).values(w).onConflictDoNothing();
    }
    logger.info({ count: wilayas.length }, "Wilayas seeded");

    // Seed categories
    for (const c of categories) {
      await db.insert(categoriesTable).values(c).onConflictDoNothing();
    }
    logger.info({ count: categories.length }, "Categories seeded");

    // Seed sellers
    for (const s of sellers) {
      await db.insert(sellersTable).values(s as any).onConflictDoNothing();
    }
    logger.info({ count: sellers.length }, "Sellers seeded");

    // Seed products
    for (const p of products) {
      await db.insert(productsTable).values(p as any).onConflictDoNothing();
    }
    logger.info({ count: products.length }, "Products seeded");

    // Seed market prices
    for (const mp of marketPrices) {
      await db.insert(marketPricesTable).values(mp as any).onConflictDoNothing();
    }
    logger.info({ count: marketPrices.length }, "Market prices seeded");

    logger.info("Database seeding completed successfully");
  } catch (error) {
    logger.error({ error }, "Error seeding database");
    throw error;
  }
}
